accounts/urls.py
from django.conf.urls import url
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r'signup/', views.signup_view, name='signup'),
    url(r'login/', views.login_view, name='login'),
    url(r'logout/', views.logout_view, name='logout')
]

articles/urls.py
from django.conf.urls import url
from . import views

app_name = 'articles'

urlpatterns = [
    url(r'^$', views.article_list, name='list'),
    url(r'create', views.create_article, name='create'),
    url(r'^(?P<slug>[\w-]+)/$', views.article_detail, name='detail'),
]

mysite/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.urls import path
from . import views
from articles import views as article_views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'admin/', admin.site.urls),
    url(r'about/$', views.about),
    url(r'accounts/', include('accounts.urls', namespace='accounts')),
    url(r'articles/', include('articles.urls', namespace='articles')),
    url(r'$', article_views.article_list, name='home'),
]   

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

articles/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=20)
    slug = models.SlugField(null=True)
    body = models.TextField()
    email = models.EmailField(null=True)
    rank = models.IntegerField(default=0)
    date = models.DateTimeField(auto_now_add=True)
    thumb = models.ImageField(default='default.png', blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=None)

    def __str__(self):
        return self.title

    def shorted_body(self):
        return self.body[:50]
    

articles/forms.py
from django import forms
from . import models

class CreateArticle(forms.ModelForm):
    class Meta:
        model = models.Article
        fields = ['title', 'slug', 'body', 'email', 'thumb']

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('articles:list')
    else:          
        form = UserCreationForm()
    return render(request, 'accounts/signup.html', {'form':form})

def login_view(request):
    if request.method =='POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('articles:list')
    else:
        form = AuthenticationForm()
    
    return render(request, 'accounts/login.html', {'form': form})

def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('articles:list')

articles/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import Article
from django.http import HttpResponse
from . import forms

# Create your views here.
def article_list(request):
    articles = Article.objects.all()

    # 1 żadanie, 2 przekierowanie, 3 przekazywanie słownika danych 
    return render(request, 'articles/article_list.html', {'articles': articles}) 

def article_detail(request, slug):
    article = Article.objects.get(slug=slug)
    return render(request, 'articles/article_detail.html', {'article': article})

@login_required(login_url='/accounts/login')
def create_article(request):
    if request.method == 'POST':
        form = forms.CreateArticle(request.POST, request.FILES)
        if form.is_valid():
            # pobieramy dane do zapisania i dajemy do zmienej i nie zapisujemy jeszcze
            # dopisujemy autora - user znajduje się w requescie
            to_save = form.save(commit=False)
            to_save.author = request.user
            to_save.save()
            return redirect('articles:list')
    else:
        form = forms.CreateArticle
    return render(request, 'articles/article_create.html', {'form': form})

mysite/views.py
from django.http import HttpResponse
from django.shortcuts import render

def homepage(request):
    return render(request, 'homepage.html')

def about(request):
    return render(request, 'about.html')

accounts/templates/accounts/login.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1>Login</h1>
    <form class='site-form' action=" {% url 'accounts:login' %} " method='post'>
        {% csrf_token %}
        {{ form }}
        {% comment %} sprawdzenie czy w linku nie ma next - chęci przejścia do kolejnej konkretnej strony {% endcomment %}
        {% if request.GET.next %}
            <input type="hidden" name='next' value="{{ request.GET.next }}">
        {% endif %}
        <input type='submit' value='Login'>
    </form>
{% endblock content %}

accounts/templates/accounts/signup.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1>Signup</h1>
    <form class='site-form' action="/accounts/signup/" method='post'>
        {% csrf_token %}
        {{ form }}
        <input type='submit' value='Signup'>
    </form>
{% endblock content %}

articles/templates/articles/article_create.html
{% extends 'base_layout.html' %}

{% block content %}
    <div class="create-article">
        <p>Pierdolnij se posta byczq </p>
        <form action="site-form" action="{% url 'articles:create' %}" method='post' enctype="multipart/form-data">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Create">
        </form>
    </div> 

    <script src='static/autoslug.js'></script>

{% endblock content %}

articles/templates/articles/article_detail.html
{% extends 'base_layout.html' %}
{% load thumbnail %}


{% block content %}
    <div class="article_detail">
        <div class="article">
            {% comment %} nie działa thumbnail {% endcomment %}
            <img src=" {{ article.thumb.url }} " alt />
            <h2> {{article.title}} </h2>
            <p> {{article.body}} </p>
            <p> {{article.date}} </p>
            <p> {{article.rank}} </p>
        </div>
    
    </div>
{% endblock content %}

articles/templates/articles/article_list.html
{% extends 'base_layout.html' %}
{% load static %}

{% block content %}
    <h1>Article List</h1>
    <div class="articles">
        {% for article in articles %}
            <div class="article">
                <h2><a href=" {% url 'articles:detail' slug=article.slug %} ">{{ article.title }}</a></h2>
                <p>{{article.shorted_body}}</p>
                <p>{{article.date}}</p>
            </div>
        {% endfor %}
    </div>
{% endblock %}

templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>About</title>
    
</head>
<body>
    
</body>
</html>

templates/base_layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}"/>
        {% comment %} <img src="{% static 'images/stars.png' %}" alt="Image"> {% endcomment %}
    </head>
    
    <body>
    <header class="wrapper">
    <h1><a href="{% url 'home' %}"><img src=" {% static 'images/logo.png' %}" alt=""></a></h1>
        <nav>
            <ul>
            {% if user.is_authenticated %}
                <li>
                    <form class='logout-link' action=" {% url 'accounts:logout' %} " method='post'>
                        {% csrf_token %}
                        <button type='submit'>Logout</button>
                    </form>
                </li>
                <li><a href="{% url 'articles:create' %}" class='new_article'>New article</a></li>
            {% else %}
                <li><a href="{% url 'accounts:login' %}">Login</a></li>
                <li><a href="{% url 'accounts:signup' %} ">Signup</a></li>  
                
            {% endif %}
            </ul>
        </nav>
        {% block content %}
        {% endblock %}    
    </div>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js" integrity="sha384-KsvD1yqQ1/1+IA7gi3P0tyJcT3vR+NdBTt13hSJ2lnve8agRGXTTyNaBYmCR/Nwi" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js" integrity="sha384-nsg8ua9HAw1y0W1btsyWgBklPnCUAFLuTMS2G72MMONqmOymq585AcH49TLBQObG" crossorigin="anonymous"></script> 
    </body>
</html>

templates/homepage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Homepage</title>
    <p>Zabawa str glowna</p>
</head>
<body>
    
</body>
</html>